[package]
name = "KFS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#sudo apt-get install fuse libfuse-dev

[dependencies]
kad4 = { path = "/home/brad/CLionProjects/rKad4" }
fuser = "0.14.0"
libc = "0.2.155"
